#!/usr/bin/env python3
"""Fetch the upstream resource packs that build.py merges, from Modrinth.

The source zips live in packs/ and are read from there by build.py via the
keys in sources.json. This script pins each of those to an exact Modrinth
version (in upstream.lock.json) and re-downloads them reproducibly, verifying
the SHA-512 Modrinth publishes for every file. packs/ is disposable — it is
rebuilt from the lock by `sync`.

Commands:
    lock                 Resolve each local zip to its Modrinth version by
                         hash and record it. Existing entries are kept unless
                         --relock is given.
    sync   (default)     Download any locked pack whose local file is missing
                         or does not match the locked hash. --force re-downloads
                         everything.
    update [SLUG ...]     Re-pin the named projects (or all) to their newest
                         version compatible with --game-version (default 26.2;
                         --any to ignore). Run sync afterwards to pull them.
    pin KEY SLUG [VER]    Lock a sources.json entry by hand, for packs `lock`
                         cannot resolve (a locally modified zip, or one not on
                         Modrinth). VER is a Modrinth version_number; omit for
                         newest compatible with --game-version.
    status               Show, per pack, the locked version and whether it
                         still lists --game-version, plus local-file drift.

The lock key is the sources.json key and is treated as a stable identifier:
the file is always written under that name regardless of Modrinth's own
filename, so build.py keeps working across version bumps. `status` reports
when Modrinth's filename has drifted from the key.
"""

import argparse
import hashlib
import json
import os
import sys
import urllib.error
import urllib.request

BASE = os.path.dirname(os.path.abspath(__file__))
SOURCES = os.path.join(BASE, "sources.json")
LOCK = os.path.join(BASE, "upstream.lock.json")
PACKS = os.path.join(BASE, "packs")
API = "https://api.modrinth.com/v2"
UA = "kgadberry/vanilla-mashup-mashup (k@kgadberry.me)"
DEFAULT_GAME_VERSION = "26.2"


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def _download(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def _hash(data, algo):
    h = hashlib.new(algo)
    h.update(data)
    return h.hexdigest()


def _primary_file(version):
    files = [f for f in version["files"] if f["primary"]] or version["files"]
    return files[0]


def _entry_from_version(version):
    f = _primary_file(version)
    return {
        "project": version["project_id"],
        "version_id": version["id"],
        "version_number": version["version_number"],
        "game_versions": version["game_versions"],
        "modrinth_filename": f["filename"],
        "url": f["url"],
        "sha1": f["hashes"]["sha1"],
        "sha512": f["hashes"]["sha512"],
    }


def _slug(project_id, cache):
    if project_id not in cache:
        cache[project_id] = _get(f"{API}/project/{project_id}").get("slug", project_id)
    return cache[project_id]


def load_sources():
    with open(SOURCES) as f:
        return list(json.load(f).get("sources", {}).keys())


def load_lock():
    if not os.path.exists(LOCK):
        return {}
    with open(LOCK) as f:
        return json.load(f).get("packs", {})


def save_lock(packs):
    ordered = {k: packs[k] for k in sorted(packs)}
    with open(LOCK, "w") as f:
        json.dump(
            {
                "_comment": "Generated by fetch.py. Pins each sources.json entry "
                "to a Modrinth version. Run 'python fetch.py sync' to materialise.",
                "packs": ordered,
            },
            f,
            indent=2,
        )
        f.write("\n")


def cmd_lock(args):
    names = load_sources()
    lock = load_lock()
    slugs = {}
    changed = 0
    for name in names:
        if name in lock and not args.relock:
            continue
        path = os.path.join(PACKS, name)
        if not os.path.isfile(path):
            print(f"skip  {name}: not in packs/ (run sync once it is locked, or "
                  f"drop the zip in packs/ and re-lock)")
            continue
        with open(path, "rb") as f:
            sha1 = _hash(f.read(), "sha1")
        try:
            version = _get(f"{API}/version_file/{sha1}?algorithm=sha1")
        except urllib.error.HTTPError as e:
            if e.code == 404:
                print(f"skip  {name}: sha1 {sha1} not known to Modrinth "
                      f"(modified locally, or not from Modrinth)")
                continue
            raise
        entry = _entry_from_version(version)
        entry["slug"] = _slug(entry["project"], slugs)
        lock[name] = entry
        changed += 1
        flag = "" if args.game_version in entry["game_versions"] else \
            f"  [!] no {args.game_version}"
        print(f"lock  {name}  ->  {entry['slug']} v{entry['version_number']}{flag}")
    if changed:
        save_lock(lock)
    print(f"\n{changed} entr{'y' if changed == 1 else 'ies'} written to "
          f"{os.path.basename(LOCK)}")


def cmd_sync(args):
    lock = load_lock()
    if not lock:
        sys.exit("nothing locked yet — run 'python fetch.py lock' first")
    names = [n for n in load_sources() if n in lock]
    missing_lock = [n for n in load_sources() if n not in lock]
    os.makedirs(PACKS, exist_ok=True)
    ok = fetched = failed = 0
    for name in names:
        entry = lock[name]
        path = os.path.join(PACKS, name)
        if not args.force and os.path.isfile(path):
            with open(path, "rb") as f:
                if _hash(f.read(), "sha512") == entry["sha512"]:
                    ok += 1
                    continue
        print(f"get   {name}  ({entry['slug']} v{entry['version_number']})")
        data = _download(entry["url"])
        got = _hash(data, "sha512")
        if got != entry["sha512"]:
            print(f"  FAIL sha512 mismatch: expected {entry['sha512'][:16]}… "
                  f"got {got[:16]}…")
            failed += 1
            continue
        with open(path, "wb") as f:
            f.write(data)
        fetched += 1
    print(f"\n{ok} up to date, {fetched} downloaded, {failed} failed")
    for name in missing_lock:
        print(f"  [!] {name} is in sources.json but not locked")
    if failed:
        sys.exit(1)


def cmd_update(args):
    lock = load_lock()
    if not lock:
        sys.exit("nothing locked yet — run 'python fetch.py lock' first")
    wanted = set(args.slugs)
    slugs = {}
    bumped = 0
    for name, entry in lock.items():
        slug = entry.get("slug") or _slug(entry["project"], slugs)
        if wanted and slug not in wanted and name not in wanted:
            continue
        versions = _get(f"{API}/project/{entry['project']}/version")
        if not args.any:
            versions = [v for v in versions
                        if args.game_version in v["game_versions"]]
        if not versions:
            print(f"---   {name} ({slug}): no version lists "
                  f"{args.game_version}; leaving at v{entry['version_number']}")
            continue
        newest = max(versions, key=lambda v: v["date_published"])
        if newest["id"] == entry["version_id"]:
            print(f"ok    {name} ({slug}): already newest "
                  f"(v{entry['version_number']})")
            continue
        new_entry = _entry_from_version(newest)
        new_entry["slug"] = slug
        print(f"bump  {name}: {slug} v{entry['version_number']} -> "
              f"v{new_entry['version_number']}")
        if new_entry["modrinth_filename"] != name:
            print(f"        note: Modrinth filename is "
                  f"'{new_entry['modrinth_filename']}' — saved as '{name}'")
        lock[name] = new_entry
        bumped += 1
    if bumped:
        save_lock(lock)
    print(f"\n{bumped} re-pinned — run 'python fetch.py sync' to download")


def cmd_pin(args):
    if args.key not in load_sources():
        sys.exit(f"'{args.key}' is not a key in sources.json")
    lock = load_lock()
    versions = _get(f"{API}/project/{args.slug}/version")
    if args.version:
        versions = [v for v in versions if v["version_number"] == args.version]
        if not versions:
            sys.exit(f"{args.slug} has no version_number '{args.version}'")
    elif not args.any:
        versions = [v for v in versions
                    if args.game_version in v["game_versions"]]
        if not versions:
            sys.exit(f"{args.slug} has no version listing {args.game_version} "
                     f"(pass a version_number, or --any)")
    entry = _entry_from_version(max(versions, key=lambda v: v["date_published"]))
    entry["slug"] = _get(f"{API}/project/{args.slug}").get("slug", args.slug)
    lock[args.key] = entry
    save_lock(lock)
    print(f"pin   {args.key}  ->  {entry['slug']} v{entry['version_number']}")
    if entry["modrinth_filename"] != args.key:
        print(f"        note: Modrinth filename is "
              f"'{entry['modrinth_filename']}' — sync will save it as '{args.key}'")


def cmd_status(args):
    lock = load_lock()
    names = load_sources()
    width = max([len(n) for n in names] + [len("pack")])
    swidth = max([len(e.get("slug", "")) for e in lock.values()] + [len("modrinth")])
    print(f"{'pack':<{width}}  {'modrinth':<{swidth}}  {'version':<12} local  flags")
    print(f"{'-' * width}  {'-' * swidth}  {'-' * 12} -----  -----")
    for name in names:
        entry = lock.get(name)
        if not entry:
            print(f"{name:<{width}}  NOT LOCKED")
            continue
        path = os.path.join(PACKS, name)
        if not os.path.isfile(path):
            local = "missing"
        else:
            with open(path, "rb") as f:
                local = "ok" if _hash(f.read(), "sha512") == entry["sha512"] \
                    else "DRIFT"
        gv = "" if args.game_version in entry["game_versions"] \
            else f"  no-{args.game_version}"
        fn = "" if entry.get("modrinth_filename", name) == name \
            else f"  mr:{entry['modrinth_filename']}"
        print(f"{name:<{width}}  {entry['slug']:<{swidth}}  "
              f"v{entry['version_number']:<11} {local}{gv}{fn}")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--game-version", default=DEFAULT_GAME_VERSION,
                   help=f"target MC version (default {DEFAULT_GAME_VERSION})")
    # No subcommand runs sync; carry its defaults so cmd_sync's attrs exist.
    p.set_defaults(func=cmd_sync, force=False)
    sub = p.add_subparsers(dest="cmd")

    lk = sub.add_parser("lock", help="resolve local zips to Modrinth versions")
    lk.add_argument("--relock", action="store_true",
                    help="re-resolve entries that are already locked")
    lk.set_defaults(func=cmd_lock)

    sy = sub.add_parser("sync", help="download locked packs that are missing/stale")
    sy.add_argument("--force", action="store_true", help="re-download everything")
    sy.set_defaults(func=cmd_sync)

    up = sub.add_parser("update", help="re-pin projects to their newest version")
    up.add_argument("slugs", nargs="*", help="project slugs (default: all)")
    up.add_argument("--any", action="store_true",
                    help="allow versions that do not list --game-version")
    up.set_defaults(func=cmd_update)

    pn = sub.add_parser("pin", help="lock one sources.json entry by hand")
    pn.add_argument("key", help="the sources.json key to lock")
    pn.add_argument("slug", help="Modrinth project slug")
    pn.add_argument("version", nargs="?", help="Modrinth version_number (default: newest)")
    pn.add_argument("--any", action="store_true",
                    help="allow a newest version that does not list --game-version")
    pn.set_defaults(func=cmd_pin)

    st = sub.add_parser("status", help="show locked versions and local drift")
    st.set_defaults(func=cmd_status)

    args = p.parse_args()
    try:
        args.func(args)
    except urllib.error.URLError as e:
        sys.exit(f"network error: {e}")


if __name__ == "__main__":
    main()
